### ISSUE TITLE
Idea on how to improve the architecture detection in sb.py

### ISSUE THREAD

**Issue by thealberto** [nccgroup/libslub#1]
Hi,
I'm trying to use `libslub` with `gdb 13.1` and I have noticed that the message reported by `gdb` isn't the expected one so the `sb.py` file raises an alert:

```
RuntimeError: Unknown architecture: The target architecture is set to "auto" (currently "i386:x86-64").
```
I have temporarily fixed my issue modifying the line 161.. I have changed the line to

```
if "The target architecture is set to \"auto\" (currently " in arch_str:
```
I'm sure that this solution isn't generic enough so I'm happy to help if needed.

Thanks

**Comment by saidelike** [comment]
Thanks for reporting this. I've pushed a more generic fix and assume it will work for you since it is simple. Please comment if you have any problem. I'm closing the issue now.
